### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by majidmp97** [ryanhugh/Arduino-SD-serial-logger#1]
I:\majiq\source\v7 with web base 8266 me\source\master\master-328\sd\Arduino-SD-serial-logger-master\Arduino-SD-serial-logger-master\serial-logger\serial-logger.ino: In function 'void makeFile()':

serial-logger:46: error: 'class SdFat' has no member named 'errorHalt_P'

 #define error(s) sd.errorHalt_P(PSTR(s))

                     ^

I:\majiq\source\v7 with web base 8266 me\source\master\master-328\sd\Arduino-SD-serial-logger-master\Arduino-SD-serial-logger-master\serial-logger\serial-logger.ino:92:9: note: in expansion of macro 'error'

         error("createContiguous failed");

         ^

serial-logger:46: error: 'class SdFat' has no member named 'errorHalt_P'

 #define error(s) sd.errorHalt_P(PSTR(s))

                     ^

I:\majiq\source\v7 with web base 8266 me\source\master\master-328\sd\Arduino-SD-serial-logger-master\Arduino-SD-serial-logger-master\serial-logger\serial-logger.ino:96:9: note: in expansion of macro 'error'

         error("contiguousRange failed");

         ^

serial-logger:46: error: 'class SdFat' has no member named 'errorHalt_P'

 #define error(s) sd.errorHalt_P(PSTR(s))

                     ^

I:\majiq\source\v7 with web base 8266 me\source\master\master-328\sd\Arduino-SD-serial-logger-master\Arduino-SD-serial-logger-master\serial-logger\serial-logger.ino:107:48: note: in expansion of macro 'error'

     if (!sd.card()->erase(bgnBlock, endBlock)) error("card.erase failed");

                                                ^

serial-logger:46: error: 'class SdFat' has no member named 'errorHalt_P'

 #define error(s) sd.errorHalt_P(PSTR(s))

                     ^

I:\majiq\source\v7 with web base 8266 me\source\master\master-328\sd\Arduino-SD-serial-logger-master\Arduino-SD-serial-logger-master\serial-logger\serial-logger.ino:109:9: note: in expansion of macro 'error'

         error("writeStart failed");

         ^

I:\majiq\source\v7 with web base 8266 me\source\master\master-328\sd\Arduino-SD-serial-logger-master\Arduino-SD-serial-logger-master\serial-logger\serial-logger.ino: In function 'void setup()':

serial-logger:126: error: 'pstr' was not declared in this scope

     cout << pstr("Free RAM: ") << FreeRam() << endl;

                              ^

I:\majiq\source\v7 with web base 8266 me\source\master\master-328\sd\Arduino-SD-serial-logger-master\Arduino-SD-serial-logger-master\serial-logger\serial-logger.ino: In function 'void loop()':

serial-logger:46: error: 'class SdFat' has no member named 'errorHalt_P'

 #define error(s) sd.errorHalt_P(PSTR(s))

                     ^

I:\majiq\source\v7 with web base 8266 me\source\master\master-328\sd\Arduino-SD-serial-logger-master\Arduino-SD-serial-logger-master\serial-logger\serial-logger.ino:162:17: note: in expansion of macro 'error'

                 error("writeData failed");

                 ^

serial-logger:46: error: 'class SdFat' has no member named 'errorHalt_P'

 #define error(s) sd.errorHalt_P(PSTR(s))

                     ^

I:\majiq\source\v7 with web base 8266 me\source\master\master-328\sd\Arduino-SD-serial-logger-master\Arduino-SD-serial-logger-master\serial-logger\serial-logger.ino:184:44: note: in expansion of macro 'error'

               if (!sd.card()->writeStop()) error("writeStop failed");

                                            ^

Multiple libraries were found for "SdFat.h"
 Used: C:\Program Files (x86)\Arduino\libraries\SdFat-1.0.6
 Not used: C:\Program Files (x86)\Arduino\libraries\SD-master
exit status 1
'class SdFat' has no member named 'errorHalt_P'

**Comment by ryanhugh** [comment]
Hmmm I haven't touched this code in a very long time. Arduino might have changed some of their libraries in he meantime. However it looks like every error you are getting is with the error function, so if you comment or change those those lines of code it might work.

**Comment by ryanhugh** [comment]
I'm going to close this due to lack of activity, feel free to re-open it!
